### ISSUE TITLE
Cascading dropdown example / guidance

### ISSUE THREAD

**Issue by smunir** [elhoutico/jhipster-primeng-blueprint#23]
Hello

Can you please provide an example or guidance for cascading dropdowns based on code generated using 
jhipster-primeng-blueprint? Thanks

**Comment by yelhouti** [comment]
@smunir that is more of a primeng question that a generator question I think, or don't I understand what you are asking?

**Comment by smunir** [comment]
@yelhouti Yes you are right but my point was to combine cascading login with lazyLoadEventToServerQueryParams() method.
