### ISSUE TITLE
Error while creating owner side of many-to-many relationship

### ISSUE THREAD

**Issue by smunir** [elhoutico/jhipster-primeng-blueprint#24]
Hello

I am getting below error **(relationshipNameCapitalized is not defined])** on generating owner side of many-to-many relationship:

> events.js:292
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: Copying template ./angular/src/main/webapp/app/entities/entity-management-update.component.html.ejs failed. [ReferenceError: /Users/shahzad/Shahzad/Personal/Projects/jhipster-primeng-blueprint/generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.html.ejs:195
>     193|                     <div class="p-col-12 p-md-10">
>     194|                         <p-multiSelect id="field_<%= relationshipFieldNamePlural %>" name="<%= relationshipFieldNamePlural %>" formControlName="<%=relationshipFieldNamePlural %>"<% if(relationships[idx].pagination !== 'no') { %>
>  >> 195|                                        [virtualScroll]="true" [lazy]="true" [rows]="10" (onLazyLoad)="on<%= relationshipNameCapitalized %>LazyLoadEvent($event)"<% } %>
>     196|                             [options]="<%= relationshipName %>Options" optionLabel="<%=otherEntityField %>">
>     197|                         </p-multiSelect>
>     198| <%_ if (relationshipRequired) { _%>
> 
> relationshipNameCapitalized is not defined]
>     at Environment.error (/Users/shahzad/git/sibgo/fe/sibgo/node_modules/yeoman-environment/lib/environment.js:243:40)
>     at module.exports.error (/Users/shahzad/Shahzad/Personal/Projects/jhipster-primeng-blueprint/node_modules/generator-jhipster/generators/generator-base.js:1542:18)

**Comment by smunir** [comment]
Please test this in JhipsterV7 changes

**Comment by yelhouti** [comment]
@smunir v7 release
