### ISSUE TITLE
Upgrade to PrimeNG 11

### ISSUE THREAD

**Issue by smunir** [elhoutico/jhipster-primeng-blueprint#26]
Hi

Do you have a plan to upgrade blueprint to prime ng 11?

**Comment by yelhouti** [comment]
Working on it, waiting for jhipster 7 to release first

**Comment by smunir** [comment]
You must have known by now, Jhipser 7 is released. I hope and pray that you may manage some time to work on this now

**Comment by yelhouti** [comment]
We are starting to work on it today

**Comment by smunir** [comment]
A few requests/suggestions:

- Entities using autogenerated numbers as PK should display ID in title of Update screen just like Detail Screen instead of readonly field
- Instead of progress spinner, use [Skeleton](https://primefaces.org/primeng/showcase/#/skeleton) on table screens
- Use [SelectButton](https://primefaces.org/primeng/showcase/#/selectbutton) instead of drop downs for Enum fields in update screens

Of course, these changed can be made in generated code but putting them in blueprint would be great and time saving.

**Comment by yelhouti** [comment]
Once v7 is working you can make a PR for each one of them, i will gladly review it
