### ISSUE TITLE
multiselect on list screens are not populating for referenced fields

### ISSUE THREAD

**Issue by smunir** [elhoutico/jhipster-primeng-blueprint#31]
multiselects for referred fields on list screen are not populating. Tested it with 7.0.2

**Comment by yelhouti** [comment]
This by design for lazy multi selectes, you should input something in the filter before

**Comment by smunir** [comment]
Oooh, I wasn't aware of that. I want a few multi selects pre-populated but [lazyLoadOnInit]="true" appears not to be working. Do I need to make some other changes too?

**Comment by yelhouti** [comment]
prepopulated by selected values or unselected ones ?

**Comment by smunir** [comment]
pre-population of all options on screen load

**Comment by yelhouti** [comment]
@smunir
Do not use lazy loading then...

And for the record, for `[lazyLoadOnInit]="true"` to work you, need to put something in the filter value. if you know what you want to have preselected you can use the new : `lazySelectedOptions`

**Comment by smunir** [comment]
Current UI isn't working well either. Please checkout these screenshots. Search button has to be clicked and filter typed without any filter field visible

<img width="303" alt="Screen Shot 2021-04-11 at 4 48 51 AM" src="https://user-images.githubusercontent.com/4279499/114287672-10032680-9a82-11eb-851c-b0396557ca3b.png">

<img width="271" alt="Screen Shot 2021-04-11 at 4 49 09 AM" src="https://user-images.githubusercontent.com/4279499/114287675-15607100-9a82-11eb-84d6-2394d65f449d.png">

<img width="302" alt="Screen Shot 2021-04-11 at 4 50 28 AM" src="https://user-images.githubusercontent.com/4279499/114287679-1e514280-9a82-11eb-8c69-e1526f505bed.png">

**Comment by smunir** [comment]
OK I will check out the fix detail. Please check out the screenshots. Closing this issue. Thanks

**Comment by yelhouti** [comment]
@smunir indeed a design, issue, I need to make i bigger to have the filter field visible

**Comment by smunir** [comment]
@yelhouti Yup a little tweaking in design is needed for this. I am not good in design and CSS, probably you would have to scarify a few minutes of your time whenever feasible
