### ISSUE TITLE
Issue generating production build while strict mode enabled

### ISSUE THREAD

**Issue by waleedamjadbutt** [elhoutico/jhipster-primeng-blueprint#4]
Hi,
First of all, I would appreciate your efforts to create this generator. I used this generator to generate one of my projects. It was successfully generated and also compiled in development mode. But when I tried creating a production build using a command: 
`npm run build`
I was facing the following issue:

![issue-prod](https://user-images.githubusercontent.com/57687653/72611379-c47bce80-394b-11ea-88fa-e5d3bbdea9ef.png)

I have taken the following steps to resolve this issue:
- Added the following code in every entity module typescript files:
`@NgModule({ schemas: [CUSTOM_ELEMENTS_SCHEMA, NO_ERRORS_SCHEMA] })`
- After that, I was facing a new issue on function `onDateSelect(dateRange: Date[], column: string, time = false)` as you can see in image:
![issue-prod-1](https://user-images.githubusercontent.com/57687653/72612356-52f14f80-394e-11ea-9638-5ff6bffc024c.png)
First solution is to change that function to `onDateSelect(dateRange?: Date[], column = '', time = false)`. Second solution is to update `tsconfig-aot.json` with following config `"strictNullChecks": false`.
- Facing issue after second issue resolved:
![issue-prod-2](https://user-images.githubusercontent.com/57687653/72612826-a7e19580-394f-11ea-9daa-ba3689c3c81a.png)
Simply do change that following constant to `const entity: any = null;`

Please let me know in case of any queries.

**NodeJS:** 12.13.0
**NPM:** 6.13.2
**Jhipster:** 6.6.0
**Angular:** 8.2.14
**Primeng:** 8.0.2
**jhipster-blueprint:** 0.2.0

**Comment by yelhouti** [comment]
@waleedamjadbutt thank you for using the blueprint, let me double check all of this, I will get right back to you

**Comment by yelhouti** [comment]
@waleedamjadbutt which version of the blueprint are you using?

**Comment by waleedamjadbutt** [comment]
@yelhouti I'm using [jhipster-blueprint](https://github.com/jhipster/generator-jhipster-blueprint) version 0.2.0

**Comment by yelhouti** [comment]
@waleedamjadbutt which version of this blueprint?

**Comment by waleedamjadbutt** [comment]
@yelhouti I'm using 0.0.18 of this blueprint.

**Comment by waleedamjadbutt** [comment]
@yelhouti Please also add a safety check against `fieldValidateRules` in `entity-management-update.component.html.ejs` because if entity fields don't have `fieldValidateRules` key this blueprint crashed with the errors. So I updated all the `fields[idx].fieldValidateRules.includes(...` to `_.includes(fields[idx].fieldValidateRules, ...)` for safety check. thanks

**Comment by yelhouti** [comment]
@waleedamjadbutt a PR is welcome

**Comment by yelhouti** [comment]
@waleedamjadbutt by the way, avoid at all cost using NO_ERRORS_SCHEMA, custom is fine and should be enough
