### ISSUE TITLE
MultiSelect doesn't show selected labels after table reset called

### ISSUE THREAD

**Issue by waleedamjadbutt** [elhoutico/jhipster-primeng-blueprint#7]
Hi,

I'm using your customized Primeng package as you implemented in your sub-generator.  Facing issue in the MultiSelect component while calling the reset function of the table. It should be display selected labels once reset table called. I replaced your customize Primeng package with the actual Primeng package and it's working fine in it. 

Following are the table header with multi-select filter options: 
`<th>
                    <p-multiSelect [options]="rateTypeOptions" [ngModel]="productTable.filters.rateType?.value"
                                   (ngModelChange)="productTable.filter($event, 'rateType', 'in')">
                        <ng-template let-rateType pTemplate="item">{{'bdmApp.RateType.' + rateType.label | translate}}</ng-template>
                    </p-multiSelect>
                </th>
                <th>
                    <p-multiSelect [options]="ratioTypeOptions" [ngModel]="productTable.filters.ratioType?.value"
                                   (ngModelChange)="productTable.filter($event, 'ratioType', 'in')">
                        <ng-template let-ratioType pTemplate="item">{{'bdmApp.RatioType.' + ratioType.label | translate}}</ng-template>
                    </p-multiSelect>
                </th>`

I used this code for reset all filters:

`<p-button id="jh-clear-filter" class="float-right jh-create-entity jh-clear-filter mr-10" (onClick)="productTable.reset()"
                  [label]="'Clear all filters'">
        </p-button>`

I tried to debug this issue in your [customize Primeng package](https://github.com/yelhouti/primeng) but not able to fix it. 

Please check the video link for this bug in detail: [Multi-Select-Issue](https://www.loom.com/share/8d277f836631492ba2eea01ecec3c5ec)

NodeJS: 12.13.0
NPM: 6.13.2
Jhipster: 6.6.0
Angular: 8.2.14
Primeng: [yelhouti/primeng](https://github.com/yelhouti/primeng/releases/download/9.0.0-rc.2/primeng-9.0.0-rc.2.tgz)
jhipster-blueprint: 0.2.0

**Comment by yelhouti** [comment]
could your provide a minimum stackblitz example?

**Comment by waleedamjadbutt** [comment]
@yelhouti I implemented the simple example in [stackblitz](https://stackblitz.com/edit/primeng-issue-mutli-select) using the actual Primeng package. Please replace the Primeng with your customize Primeng package and only check the representative column to reproduce the bug. I'm also attaching the example project [link](https://we.tl/t-RgcauNdD0o) and that link will expire in 7 days :). Please also update your customize Primeng package with the latest one.

**Comment by yelhouti** [comment]
@waleedamjadbutt I trie reproducing it: https://primeng-issue-mutli-select-tp5rt3.stackblitz.io
No luck, I used your code with my library... could you update yur stackblitz with an example that is not working....

**Comment by waleedamjadbutt** [comment]
@yelhouti In my [stackbliz ](https://stackblitz.com/edit/primeng-issue-mutli-select) I used actual Primeng. I tried to open this link [https://primeng-issue-mutli-select-tp5rt3.stackblitz.io/](https://primeng-issue-mutli-select-tp5rt3.stackblitz.io/) and it's not working for me. If you download the project that I attached in the above link you will see the issue that multi-select will not show selected labels after reset table function called.

**Comment by yelhouti** [comment]
try this please: https://stackblitz.com/edit/primeng-issue-mutli-select-tp5rt3

**Comment by waleedamjadbutt** [comment]
@yelhouti I checked your stackbliz ad you install the actually Primeng not your customize Primeng package. Please run it in your local machine using your customize package and you will able to reproduce it. thanks

**Comment by yelhouti** [comment]
@waleedamjadbutt it seems liks stackblitz doesn take into account changes to package.json, trying locally...

**Comment by yelhouti** [comment]
@waleedamjadbutt contact me on gitter please

**Comment by waleedamjadbutt** [comment]
@yelhouti Thank you for your time and figuring out the issue it seems great. Could you please update your package to 9.0.5 so that I can update accordingly?

**Comment by ikashifullah** [comment]
Hi @yelhouti and @waleedamjadbutt,

  Any progress on this, I am having the same issue.

**Comment by yelhouti** [comment]
@ikashifullah @waleedamjadbutt sorry it took this long, should be fixed using version:
https://github.com/yelhouti/primeng/releases/download/9.0.6/primeng-9.0.6.tgz
please update it manually for now, blueprint will be updated later once angular9 support is working perfectly
Many improvement with multiselect like: showing selected Items once lazy loaded...
